### ISSUE TITLE
The bot does not respond after a while

### ISSUE THREAD

**Issue by ChetAlv** [freetnt5852/LadyBug-Bot#26]
Hey, I'm new to programming so maybe the solution is in front of me but I'm ignoring it, I hope you can help me

The clone I made of the bot is going great and I was in charge of translating it a little into Spanish, it happens that after a while that it has been on, it simply stops responding. The cleanup log still works but there is no way for it to respond to commands.
As I said I am new to javascript so forgive me if the solution is as simple as changing a line

Thanks for the bot and I wait for an answer.

**Comment by ravener** [comment]
That sort of problems are really hard to identify. Is there any errors in your terminal?

**Comment by ChetAlv** [comment]
No, the terminal does not show me anything other than the cache cleanings

I think i found it.
The bot in --dev mode does not cause this problem
The 401 error of the DBL api is the only one I get when starting the bot normally but after a while it makes it stop responding if I am not wrong.
I thought nothing would happen but that should be so?

**Comment by ravener** [comment]
The 401 error is because your bot is not in DBL, set nothing as the DBL key in env and it will not use that feature. Damn everyone gets this I should set the DBL field empty by default in the example env rather than that placeholder

**Comment by ChetAlv** [comment]
Well, I didn't know that getting that error would turn off the bot's commands after a while, since I had no plans to publish it exactly now in dbl.

I will make the modifications that I thought and be able to try some others and then publish it.
Still thank you and yes, you should clear that field.

I close this issue. 👋

**Comment by ravener** [comment]
The reason it happens after a while is because at first DBL api is not called in at all so everything is fine but there's an interval to post bot stats every few mins or so, that's when it tries to call the api and crashes
