### ISSUE TITLE
num.replace not function v11 to v12

### ISSUE THREAD

**Issue by EmojiPati** [freetnt5852/LadyBug-Bot#27]
commands have an num.replace not function ​​error 
I got the error in the anime search command error line
https://github.com/ravener/miyako/blob/135b3648e40eb5cff7a141d81a318f032df52a11/src/structures/Command.js#L114

**Comment by ravener** [comment]
I was aware of that issue for long but i didn't properly read the stack trace I thought the API response changed and so I became lazy to fix it. But that was a very simple mistake, I just pushed a fix.
