### ISSUE TITLE
welcome and other stuff outdated

### ISSUE THREAD

**Issue by mysteiige** [freetnt5852/LadyBug-Bot#5]
welcome msgs, leave msg, and modlog stuff is outdated. past pr 383 on klasa master

**Comment by ravener** [comment]
@b1nzy1sba3 what do you mean? they are updated.

**Comment by mysteiige** [comment]
async init() with schema inside is unsupported

**Comment by ravener** [comment]
It's not there

**Comment by mysteiige** [comment]
usaidwhat
wait
fuck
this is the wrong cucking bot. FUCK ME
